version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"
    logging:
      driver: "none"

  postgres:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data
    logging:
      driver: "none"

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - postgres

  api-gateway:
    build:
      context: ./
      dockerfile: ./apps/api-gateway/Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./apps/api-gateway/.env
    depends_on:
      - rabbitmq
      - postgres
      - users
    command: npm run start:dev api-gateway

  users:
    build:
      context: ./
      dockerfile: ./apps/users/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - ./apps/users/.env
    depends_on:
      - rabbitmq
      - postgres
    command: npm run start:dev users

volumes:
  pgdata: