version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "15672:15672"
      - "5672:5672"

  postgres:
    image: postgres:13
    env_file:
      - .env
    volumes:
      - pgdata:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    env_file:
      - .env
    ports:
      - "5050:80"
    depends_on:
      - postgres

  api-gateway:
    build:
      context: ./
      dockerfile: ./apps/api-gateway/Dockerfile
    ports:
      - "4001:4001"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
      - ./apps/api-gateway/.env
    depends_on:
      - rabbitmq
      - postgres
      - users
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "npm", "run", "start:dev", "api-gateway"]

  users:
    build:
      context: ./
      dockerfile: ./apps/users/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
      - ./apps/users/.env
    depends_on:
      - rabbitmq
      - postgres
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "npm", "run", "start:dev", "users"]

  sensors:
    build:
      context: ./
      dockerfile: ./apps/sensors/Dockerfile
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    env_file:
      - .env
      - ./apps/sensors/.env
    depends_on:
      - rabbitmq
      - postgres
    command: ["./wait-for-it.sh", "rabbitmq:5672", "--", "npm", "run", "start:dev", "sensors"]

volumes:
  pgdata: