export enum RoomTypeEnum {
  LivingRoom = 'Living Room',
  Kitchen = 'Kitchen',
  Bedroom = 'Bedroom',
  Bathroom = 'Bathroom',
  DiningRoom = 'Dining Room',
  HomeOffice = 'Home Office',
  Garage = 'Garage',
  Basement = 'Basement',
  Attic = 'Attic',
  GuestRoom = 'Guest Room',
  Hallway = 'Hallway',
  LaundryRoom = 'Laundry Room',
  Pantry = 'Pantry',
  PlayRoom = 'Play Room',
  StorageRoom = 'Storage Room',
  Gym = 'Gym',
  HomeTheater = 'Home Theater',
  Garden = 'Garden',
  Balcony = 'Balcony',
  Other = 'Other',
}
