export enum SensorsCommunicationEnum {
  CREATE_SENSOR = 'createSensor',
  GET_SENSOR_BY_ID = 'getSensorById',
  SENSOR_LIST = 'sensorList',
  ADD_DHT_DATA = 'addDhtData',
  GET_LATEST_DHT_DATA = 'getLatestDhtData',
  DHT_SENSOR_LIST = 'dhtSensorList',
  ADD_PIR_DATA = 'addPirData',
  PIR_SENSOR_LIST = 'pirSensorList',
  ADD_SMOKE_DATA = 'addSmokeData',
  SMOKE_SENSOR_LIST = 'smokeSensorList',
  ADD_REED_SWITCH_DATA = 'addReedSwitchData',
  GET_LATEST_REED_SWITCH_DATA = 'getLatestReedSwitchData',
  REED_SWITCH_LIST = 'reedSwitchList',
  GET_LIGHT_STATE = 'getLightState',
  CHANGE_LIGHT_STATE = 'changeLightState',
  LIGHT_LIST = 'lightList',
  CHANGE_ALARM_STATE = 'changeAlarmState',
  GET_ALARM_STATE = 'getAlarmState',
  ALARM_LIST = 'alarmList',
}
